### ISSUE TITLE
Label should support "tiny", "small", "medium", and "large" sizes

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#96]

**Comment by fraincs** [comment]
Mini will need to be added in order to support labels in Tabs

![image](https://user-images.githubusercontent.com/361632/72121521-46a33c00-3329-11ea-83b7-88a36eb5ad90.png)

**Comment by fraincs** [comment]
BTW Medium is not a size that does something.

**Comment by fraincs** [comment]
Fixed on reason-of-creation-feature-support

**Comment by patricklafrance** [comment]
I think you forgot to push:

![image](https://user-images.githubusercontent.com/794579/72174298-62e5be00-33a7-11ea-9bd6-a3cdb344049e.png)
